# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-DNS-Server
version:      1.46
version_from: Server.pm
installdirs:  site
requires:
    Net::DNS:                      0.38
    Net::DNS::Method:              0
    NetAddr::IP:                   3

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
